### ISSUE TITLE
Thank you for this, however it is throwing up an error for me

### ISSUE THREAD

**Issue by ghost** [Donohue/alexa#3]
Hi Donohue,

Thank you so much for the code provided here. Unfortunately after running it through the utterance testing section, I am getting the following error: "The remote endpoint could not be called, or the response it returned was invalid."

Is there any obvious reason why this might be happenning?

P.S. I realise I have posted a comment on the Medium post regarding the same thing, but was hoping that more people may see this and also be able to add their two cents.

**Comment by ghost** [comment]
FIXED

Somehow, the Lambda function had two lines at the very bottom which had come un commented. Mentioning the Github trademarks. I commented them out, ran the Test again, and Alexa sang!

Thank you for providing me with this code. Will see what I can build.

**Comment by Donohue** [comment]
Glad to hear you figured it out :-)
