### ISSUE TITLE
Same like alexa/skill-sample-nodejs-hello-world?

### ISSUE THREAD

**Issue by DanielRuf** [Donohue/alexa#4]
It looks like they do the same and https://github.com/alexa/skill-sample-nodejs-hello-world supersedes this here and it is actively maintained and there are relatively new contributions.

**Comment by Donohue** [comment]
Thanks for the heads up – this project is still pretty helpful for people with no coding experience, so still think it's worth leaving up even though it's unmaintained.

**Comment by DanielRuf** [comment]
Definitely, you are right.
